In [6]:
a = [1,2,3,4,5,6,7,8,9,10]

In [7]:
b=[]
for num in a :
    b.append(num*5)
b

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [3]:
import numpy as np

In [10]:
a= np.array([1,2,3,4,5,6,7,8,9,10])
a*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [11]:
numpyArray = np.array([22,44,55,66])
print(numpyArray)
type(numpyArray)

[22 44 55 66]


numpy.ndarray

In [13]:
numpyArray = np.array([22,44.89,55,66])
print(numpyArray)
(numpyArray)

[22.   44.89 55.   66.  ]


array([22.  , 44.89, 55.  , 66.  ])

In [16]:
numpyArray = np.array([22,44,55,66], dtype = "float32")
print(numpyArray)
(numpyArray)

[22. 44. 55. 66.]


array([22., 44., 55., 66.], dtype=float32)

In [17]:
numpyArray = np.array([22,44,55.2,66], dtype = "int32")
print(numpyArray)
(numpyArray)

[22 44 55 66]


array([22, 44, 55, 66])

In [21]:
numpyArray = np.array([22,44.98,55,66], dtype = "float32")
print(type(numpyArray))
(numpyArray)  # nd is n dimentional ;float 32 32 is size

<class 'numpy.ndarray'>


array([22.  , 44.98, 55.  , 66.  ], dtype=float32)

In [22]:
numpyArray = np.array([22,44,55.2,66], dtype = "int8")
print(type(numpyArray))
(numpyArray)

<class 'numpy.ndarray'>


array([22, 44, 55, 66], dtype=int8)

In [23]:
numpyArray = np.array([22,44,55.2,66], dtype = np.int8)
print(type(numpyArray))
(numpyArray)

<class 'numpy.ndarray'>


array([22, 44, 55, 66], dtype=int8)

In [24]:
#in the above there r ways to define type in quotations and without quotes

In [28]:
randomArray = np.random.randn(10) #it creates distribution
randomArray

array([-0.16462322, -1.76896837, -0.0942602 ,  0.82761338,  0.61304547,
        0.52586024,  0.01143092,  1.86240297,  1.9738445 ,  0.50551333])

In [31]:
randomArray = np.random.randn(10)*100 #it creates distribution
randomArray

array([  41.62083107,   37.24195879,   21.00337713, -228.68754073,
       -111.36471243,  -34.77844008,  -58.36857388,  -88.42278914,
       -118.0070189 ,    6.97943747])

In [33]:
randomArray.ndim


1

In [35]:
randomArray = np.random.randn(3) #it creates distribution
randomArray
randomArray.shape  (3,means 1 dimentional)

(3,)

In [37]:
#array>> vector  (1D)
#matrix>> tensor(Multi dimentional)

In [38]:
#making tensor twoD means here is 2d means x n y axis
twoD = np.array([[1,2,3],[4,5,6],[7,8,9],[2,3,4]])
twoD

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4]])

In [39]:
twoD.shape #[] is rows and values column

(4, 3)

In [43]:
zeroD = np.array(100)
print (zeroD.ndim)    #dimension is 0 
zeroD.shape #() ki koi shape nhi, scalar ki koi shape nhi

0


()

In [44]:
miscD = np.array([99]) # 1 dimentional can b x or y;element is single
print(miscD)
print(miscD.ndim)
print(miscD.shape) #comma means vector

[99]
1
(1,)


In [45]:
miscD = np.array([[99]]) # now its 2dimentional x and y axid means matrix; element is single 
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[99]]
2
(1, 1)


In [48]:
miscD = np.array([[[99]]]) # now its 3dimentional x and y and z axis means matrix; element is single 
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[99]]]
3
(1, 1, 1)


In [49]:
miscD = np.array([[[[99]]]]) # now its 4dimentional x and y and z and 1 more axis means matrix; element is single 
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[[99]]]]
4
(1, 1, 1, 1)


In [50]:
a = np.arange(10)  # in python range ;here in numpy use arange
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
#to make it tensor
a = np.arange(12).reshape(4,3)  # in python range ;here in numpy use arange;pairs 6x2 4x3 3x4 2x6
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
#sedha krdena
flat = np.ravel(a) 
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
z = np.array([22,33,44,55,666,77])
z

array([ 22,  33,  44,  55, 666,  77])

In [59]:
rz = z.reshape(2,3)
rz

array([[ 22,  33,  44],
       [ 55, 666,  77]])

In [62]:
fz = np.ravel(rz) # 6 elements
fz

array([ 22,  33,  44,  55, 666,  77])

In [68]:
#2d to flat(1d) then 3d then back to 2d?
twoD = np.arange(36).reshape(6,6)
twoD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [69]:
threeD = twoD.reshape(3,3,4) # 3x3x4 =36
threeD  #0 11 is 2d here thrree 2Ds hen to 3d bngya

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [70]:
rebacktwoD = threeD.reshape(6,6)
rebacktwoD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [75]:
threeD = np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                   [[3,56,8],
                    [8,7,6],
                    [9,8,7]]])
threeD #3 d k andar dou 2ds hen n wo 2ds k andar 1  dimensionsl thy

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 3, 56,  8],
        [ 8,  7,  6],
        [ 9,  8,  7]]])

In [77]:
#[[]] 2d 
#[[[],
  #[]]]  #jitne number of brackets utne number of dimensions

In [78]:
#twoD + twoD
twoD + twoD

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46],
       [48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70]])

In [79]:
twoD - twoD

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [80]:
twoD / twoD

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [81]:
twoD * twoD

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [82]:
twoD ** twoD


array([[          1,           1,           4,          27,         256,
               3125],
       [      46656,      823543,    16777216,   387420489,  1410065408,
         1843829075],
       [ -251658240, -1692154371, -1282129920,  1500973039,           0,
         1681328401],
       [  457441280,  -306639989,           0,   878082373,   977272832,
        -1276351769],
       [          0,  1296002393,   603979776,  -714244925,           0,
        -1266004979],
       [ 1073741824, -2010103841,           0,   942687265,           0,
          618402555]], dtype=int32)

In [84]:
2**3

8

In [85]:
twoD // twoD

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([[0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [86]:
3//2

1

In [89]:
m1 = np.arange(12).reshape(4,3)
m2 = np.random.randn(12).reshape(4,3)
m1 + m2

array([[-0.23424614,  0.54590787,  1.07646353],
       [ 4.74163178,  5.34440551,  4.33508293],
       [ 5.40224038,  7.01571992,  9.51759834],
       [ 8.48302925,  9.40475408,  9.45327268]])

In [90]:
m1 = np.arange(12).reshape(4,3)
m2 = np.random.randn(16).reshape(4,4)
m1 + m2 # error bcz addition etc k liye same shape is necessary

ValueError: operands could not be broadcast together with shapes (4,3) (4,4) 

In [93]:
#in multiplaction of matrix first row elements  equal to first coloumn elements 2x3 2x3 se nhji hnge multiply
# order is shape

In [96]:
m3 = np.arange(18).reshape(3,6)
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [97]:
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [100]:
m1 @  m3 # mirror multiplcation * krta he (same shape honi chahean ..
#@ matriz  multiplcation ye krta means same shape nhi b ho but 1st mtrix k comun se 2nd ki row brabr ho

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [102]:
m3 @m1

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 6)

In [103]:
# same shape mei @ use krenge tu anwer diff aega bcz @ wali wo he jo hum krte hen copy pe.
#mirror jo ha index to index krta he ,

In [104]:
np.dot(m1,m3) # other way

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [108]:
m1.dot(m3) # other way

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [109]:
#builtin matrix zero
zeroos = np.zeros(4)
zeroos

array([0., 0., 0., 0.])

In [110]:
#builtin matrix
zeroos = np.zeros(4,dtype = "int8")
zeroos

array([0, 0, 0, 0], dtype=int8)

In [113]:
#builtin matrix now 2d 
zeroos = np.zeros((4,5),dtype ="int8")
zeroos

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [114]:
onees = np.ones((4,5),dtype ="int8") # tuple he 4 5 dor n d
onees

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [115]:
onees = np.ones((4,5),dtype ="int8") # tuple he 4 5 dor n d
onees*50

array([[50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50]], dtype=int8)

In [117]:
fulll = np.full((4,4),50)  #other way kis se full kra he 
fulll

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

In [118]:
fulll = np.full((4,4),50)  #other way kis se full kra he 
fulll *2

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [120]:
emptyy = np.empty((4,4,4))
emptyy # empty create zero but bcz of garbage value(no reference)show those also


array([[[3.9031e-322, 0.0000e+000, 4.9407e-324, 8.0953e-320],
        [0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000],
        [0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000],
        [0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000]],

       [[0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000],
        [0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000],
        [0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000],
        [0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000]],

       [[0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000],
        [0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000],
        [0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000],
        [0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000]],

       [[0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000],
        [0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000],
        [0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000],
        [0.0000e+000, 0.0000e+000, 0.0000e+000, 0.0000e+000]]])

In [121]:
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [122]:
like = np.zeros_like(m3)
like  # zero like measn creates zeros but shape and data type uthatega m3 ki 

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [123]:
likee = np.ones_like(m3)
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [126]:
i = np.eye(5,5) #idenetity diagnol 1 n determinant ans is 1
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [128]:
 # change data type of matriz
j = i.astype("int")
j

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [129]:
i >j

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [130]:
j>i

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [132]:
m1 > m3

ValueError: operands could not be broadcast together with shapes (4,3) (3,6) 

In [133]:
# for bool shape should be same

# basic indexing and slicing

In [134]:
alist = [99,77,55,33,11]
alist[0]


99

In [135]:
type(alist[0])

int

In [136]:
type(alist[0:3])

list

In [137]:
#indexing se value ati he jo data type apni hogi jo k int he 
#in slicing return jid data type ka slice woi hoga mtlb list se list niklega
#pizza ka slice pizza he but pizza se mushroom pizza nhi he

In [138]:
tdarray = np.arange(36).reshape(6,6)
tdarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [139]:
#to identify 20 thsi is indexing 3rd row n 2nd column satrts from 0 
tdarray[3,2]

20

In [140]:
#slicing 13 14 15 19 20 21 26 27 28 (3x3 matrix)
#tdarray[row,colomn]
#tdarray[start:end, start:end]
tdarray[2:5, 1:4] # end at 5 means 4  tk 5 not included

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [141]:
#33 usind slicing
tdarray[5:,3:4] # 33 aega but value nhi he 2 dimentional array aega

array([[33]])

In [142]:
tdarray[1:2,2:5]

array([[ 8,  9, 10]])