In [1]:
import numpy as np


In [2]:
arr2d = np.array([[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[7,5,1,6,5],[8,2,4,9,7]])

In [3]:
arr2d

array([[ 2,  4,  6,  8, 10],
       [ 1,  2,  3,  4,  5],
       [ 4,  0,  6,  2,  5],
       [ 7,  5,  1,  6,  5],
       [ 8,  2,  4,  9,  7]])

In [6]:
arr2d[2:4,1:4]

array([[0, 6, 2],
       [5, 1, 6]])

In [8]:
arr2dnew = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24],[25,26,27,28,29,30],[21,32,33,34,35,36]])
arr2dnew

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [21, 32, 33, 34, 35, 36]])

In [10]:
arr = np.arange(1,37).reshape(6,6)
arr


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [11]:
arr[2:3,0:] #row,colom count with index that starts with zero : 3 select nhi hogi

array([[13, 14, 15, 16, 17, 18]])

In [12]:
arr[2:4,0:]

array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [13]:
arr[2:4,0:6]

array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [15]:
arr[4:5,:] # khali colon in colum means all colomn

array([[25, 26, 27, 28, 29, 30]])

In [16]:
arr[4:5,]

array([[25, 26, 27, 28, 29, 30]])

In [17]:
arr[4:5]

array([[25, 26, 27, 28, 29, 30]])

In [19]:
arr[4] # it knows its a row

array([25, 26, 27, 28, 29, 30])

In [23]:
arr[:2]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [27]:
arr[1:5,]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [28]:
arr[2:4,5:]  # it gives in 2 dimentional  values same as below one

array([[18],
       [24]])

In [31]:
arr[2:4,5] # it gives u vector 1 Dimentional

array([18, 24])

In [34]:
arr[:,:-2]

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10],
       [13, 14, 15, 16],
       [19, 20, 21, 22],
       [25, 26, 27, 28],
       [31, 32, 33, 34]])

In [35]:
arr[:,:2]

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [39]:
arr[:,::2] #double colon=1 colon is for column another is for step

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [40]:
arr[:,::-2]

array([[ 6,  4,  2],
       [12, 10,  8],
       [18, 16, 14],
       [24, 22, 20],
       [30, 28, 26],
       [36, 34, 32]])

In [41]:
arr[:,::3] # for colum step

array([[ 1,  4],
       [ 7, 10],
       [13, 16],
       [19, 22],
       [25, 28],
       [31, 34]])

In [43]:
# for row step
arr[::2,::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [47]:
arr[::2,0:]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18],
       [25, 26, 27, 28, 29, 30]])

In [48]:
arr[0:4:4,0:]

array([[1, 2, 3, 4, 5, 6]])

In [49]:
arr[0:4:4,0:4:2]

array([[1, 3]])

In [50]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

# boolean indexing

In [53]:
# book example page 112
#two array one is name n one is number
names = np.array(['Bob','Joe','Will','Bob','Joe','Joe'])
names                  
                  

array(['Bob', 'Joe', 'Will', 'Bob', 'Joe', 'Joe'], dtype='<U4')

In [56]:
data = np.random.randn(7,4)
data

array([[ 0.38084731,  1.23305186,  1.03601761,  0.14022   ],
       [ 1.04526616, -0.44591633, -1.09427584,  0.97008058],
       [ 2.60633618, -0.68599493,  0.03701172, -1.24034946],
       [ 0.25085466, -0.84731771,  0.11652703, -0.22315252],
       [ 0.20274646, -0.99789529, -0.68983304, -0.91819157],
       [ 0.08440393, -1.04693259,  0.26419956,  2.58237277],
       [ 0.80883918,  2.16484251,  1.18837919,  0.25320644]])

In [65]:
data[True,False,False,False,False,True,False] #jo row humko uthani thi us mei trye likha
#first true means first row

array([], shape=(0, 7, 4), dtype=float64)

In [69]:
bol = np.array([True,False,False,False,False,True,False],dtype = "bool")
data[bol]

array([[ 0.38084731,  1.23305186,  1.03601761,  0.14022   ],
       [ 0.08440393, -1.04693259,  0.26419956,  2.58237277]])

In [57]:
names == 'Bob' #isko b ye numbers ki form mei lega

array([ True, False, False,  True, False, False])

In [58]:
data>1

array([[False,  True,  True, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False,  True,  True, False]])

In [59]:
#for values nikalni he exact not location  tu dobara data k frame  mei rakhna orega
data[data>1]

array([1.23305186, 1.03601761, 1.04526616, 2.60633618, 2.58237277,
       2.16484251, 1.18837919])

In [61]:
names=="Bob" now this answer we put in data tu row index 0 iska dat dipslay krado

array([ True, False, False,  True, False, False])

In [64]:
data[names=='Bob']

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 6