# Revision

In [2]:
import numpy as np

In [3]:
arr1d = np.array([44,55,66,77])
arr1d

array([44, 55, 66, 77])

In [4]:
arr1d[2]

66

In [5]:
arr1d[3]

77

In [6]:
arr1d[-1]

77

In [8]:
arr1d[-2]

66

In [10]:
arr1d[2:4]

array([66, 77])

In [14]:
arr2d = np.array([[22,33,44],[55,66,77]])
print(arr2d)

[[22 33 44]
 [55 66 77]]


In [15]:
arr2d[1][2]

77

In [62]:
arr2d[0:,2:]

array([[44],
       [77]])

In [16]:
#another method :this is not slicing
arr2d[1,2]

77

In [20]:
arr2d[:2]

array([[22, 33, 44],
       [55, 66, 77]])

In [21]:
arr2d[:2,1:]

array([[33, 44],
       [66, 77]])

In [22]:
arr2d[:2,1]

array([33, 66])

In [46]:
arr2d[1:,1:]

array([[66, 77]])

### arr2d[3:,2:]

In [27]:
arr3d = np.array([[[10,20,30],[40,50,60],[70,80,90]]])
arr3d

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [28]:
arr3d.shape

(1, 3, 3)

In [29]:
arr3d.ndim

3

In [34]:
arr3d[0][2]

array([70, 80, 90])

In [35]:
arr3d[2] #erroe bcz aik 2d rray tha is me

IndexError: index 2 is out of bounds for axis 0 with size 1

In [44]:
arr2d[1][1]

66

In [49]:
arr2d[1,1:3]

array([66, 77])

In [51]:
arr3d[1][1][0]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [52]:
arr3d[:2]

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [53]:
arr3d[0,:2] #0 means first 2d array :2 first 2 rows

array([[10, 20, 30],
       [40, 50, 60]])

In [54]:
arr3d[0,:2,1:2]

array([[20],
       [50]])